#!/bin/bash

echo -e  ' \t' "    _    ____  ___ ____     ____ _     _____    _    _   _ _____ ____   "
echo -e  ' \t' "   / \  |  _ \|_ _/ ___|   / ___| |   | ____|  / \  | \ | | ____|  _ \  "
echo -e  ' \t' "  / _ \ | |_) || |\___ \  | |   | |   |  _|   / _ \ |  \| |  _| | |_) | "
echo -e  ' \t' " / ___ \|  _ < | | ___) | | |___| |___| |___ / ___ \| |\  | |___|  _ <  "
echo -e  ' \t' "/_/   \_\_| \_\___|____/   \____|_____|_____/_/   \_\_| \_|_____|_| \_\ "
echo
echo "Enter The JSON block below"
echo
array=()
while IFS= read -r -p "" url; do
    [[ $url ]] || break
    array+=("$url")
done

grab=$(printf ' %s\n' "${array[@]}")
printf "%`tput cols`s"|tr ' ' '-';
echo
echo

for i in $(echo $grab); do echo "$i" >> grabtime.txt; done

time=$(cat grabtime.txt | grep -A1 'timestamp' | grep -v 'timestamp' | sed 's/\"//g;')
region=$(cat grabtime.txt | grep -A1 'region' | grep -v 'region' | sed 's/\"//g;')
account=$(cat grabtime.txt | grep -A1 'ownerAccountId' | grep -v 'ownerAccountId' | sed 's/\"//g;')
type=$(cat grabtime.txt | grep -A1 'type' | grep -v 'type' | sed 's/\"//g;')
instance=$(cat grabtime.txt | grep -A1 'instanceName' | grep -v 'instanceName' | sed 's/\"//g;')
function=$(cat grabtime.txt | grep -A1 'functionName' | grep -v 'functionName' | sed 's/\"//g;')
newdate=$(echo "@"$time)

date -d $newdate
echo "Region:" $region
echo "AWS Account ID:" $account
echo "Instance Name:" $instance
echo "Function Name:" $function
echo "Type:" $type
echo
rm grabtime.txt
printf "%`tput cols`s"|tr ' ' '-';
echo
echo "Done!"
