#!/bin/bash

echo -e  ' \t' "    _    ____  ___ ____     ____ _     _____    _    _   _ _____ ____   "
echo -e  ' \t' "   / \  |  _ \|_ _/ ___|   / ___| |   | ____|  / \  | \ | | ____|  _ \  "
echo -e  ' \t' "  / _ \ | |_) || |\___ \  | |   | |   |  _|   / _ \ |  \| |  _| | |_) | "
echo -e  ' \t' " / ___ \|  _ < | | ___) | | |___| |___| |___ / ___ \| |\  | |___|  _ <  "
echo -e  ' \t' "/_/   \_\_| \_\___|____/   \____|_____|_____/_/   \_\_| \_|_____|_| \_\ "
echo
echo "Enter The JSON block below"
echo

#make an array to recieve multiline block
array=()
while IFS= read -r -p "" url; do
    [[ $url ]] || break
    array+=("$url")
done

grab=$(printf ' %s\n' "${array[@]}")
printf "%`tput cols`s"|tr ' ' '-';
echo
echo

#parse array into text
for i in $(echo $grab); do echo "$i" >> grabtime.txt; done

#get the values out
time=$(cat grabtime.txt | grep -A1 'timestamp' | grep -v 'timestamp' | sed 's/\"//g;')
region=$(cat grabtime.txt | grep -A1 'region' | grep -v 'region' | sed 's/\"//g; s/,*$//g;')
account=$(cat grabtime.txt | grep -A1 'ownerAccountId' | grep -v 'ownerAccountId' | sed 's/\"//g; s/,*$//g;')
type=$(cat grabtime.txt | grep -A1 'type' | grep -v 'type' | sed 's/\"//g;')
instance=$(cat grabtime.txt | grep -A1 'instanceName' | grep -v 'instanceName' | sed 's/\"//g; s/,*$//g;')
function=$(cat grabtime.txt | grep -A1 'functionName' | grep -v 'functionName' | sed 's/\"//g; s/,*$//g;')
instancetype=$(cat grabtime.txt | grep -A1 'instanceType' | grep -v 'instanceType' | sed 's/\"//g; s/,*$//g;')
instanceid=$(cat grabtime.txt | grep -A1 'instanceId' | grep -v 'instanceId' | sed 's/\"//g; s/,*$//g;')
legacyid=$(cat grabtime.txt | grep -A1 'domainId' | grep -v 'domainId' | sed 's/\"//g; s/,*$//g;')
state=$(cat grabtime.txt | grep -A1 'currentState' | grep -v 'currentState' | sed 's/\"//g; s/,*$//g;')
stopstart=$(cat grabtime.txt | grep -A1 'currentStartStopCount' | grep -v 'currentStartStopCount' | sed 's/\"//g; s/,*$//g;')
domainstate=$(cat grabtime.txt | grep -A1 'currentDomainState' | grep -v 'currentDomainState' | sed 's/\"//g; s/,*$//g;')
accesspoint=$(cat grabtime.txt | grep -A1 'accessPointId' | grep -v 'accessPointId' | sed 's/\"//g; s/,*$//g;')
accesspointname=$(cat grabtime.txt | grep -A1 'accessPointName' | grep -v 'accessPointName' | sed 's/\"//g; s/,*$//g;')
elbname=$(cat grabtime.txt | grep -A1 'dnsName' | grep -v 'dnsName' | sed 's/\"//g; s/,*$//g;')
newdate=$(echo "@"$time)
date2=$(date -d $newdate)

#decide blocks
if [[ $type == "Ec2Instance" ]];
then
        echo "Resource Type: EC2"
        echo "AWS Account ID:" $account
        echo "Instance Type:" $instancetype
        echo "Instance Name:" $instanceid
        echo "Legacy ID:" $legacyid
        echo "State:" $state
        echo "Region:" $region
        echo "Domain State:" $domainstate
        echo "Start - Stops:" $stopstart
        echo "Time Stamp:" $date2

elif [[ $type == "LightsailInstance" ]];
then
        echo "Resource Type: LightSail"
        echo "Instance Name:" $instance
        echo "AWS Account ID:" $account
        echo "Region:" $region
        echo "Time Stamp:" $date2

elif [[ $type == "LambdaFunction" ]];
then
        echo "Resource Type: Lamda Function"
        echo "Function Name:" $function
        echo "AWS Account ID:" $account
        echo "Region:" $region
        echo "Time Stamp:" $date2
elif [[ $type == "ElasticLoadBalancer" ]];
then
        echo "Resource Type: Elastic Load Balancer"
        echo "Access Point:" $accesspoint
        echo "Access Point Name:" $accesspointname
        echo "AWS Account ID:" $account
        echo "ELB Name:" $elbname
        echo "Region:" $region
        echo "Time Stamp:" $date2
else
        echo "Resource not detected correctly - ping beta channel"
fi
echo

rm grabtime.txt
printf "%`tput cols`s"|tr ' ' '-';
echo
echo "Done!"
