#!/bin/bash

echo -e "       _               _   "
echo -e "  __ _| |__   ___  ___| |_ "
echo -e " / _  |  _ \ / _ \/ __| __|"
echo -e "| (_| | | | | (_) \__ \ |_ "
echo -e " \__, |_| |_|\___/|___/\__|"
echo -e " |___/                     "

echo
echo "If you would like to report an error ping drampil on slack."
echo
echo "Check the hosts of an IP address list."
echo "one entry per line"
echo "> To initiate press enter twice."
echo "---"

array=()
while IFS= read -r -p "" url; do
    [[ $url ]] || break
    array+=("$url")
done

grab=$(printf ' %s\n' "${array[@]}")
printf "%`tput cols`s"|tr ' ' '-';
echo
echo
for i in $(echo $grab); do echo "$i";
echo "$(whois $i | grep -m 1 'OrgName\|org-name\|mnt-by\|person' | awk {'print $2'})"
echo; done

printf "%`tput cols`s"|tr ' ' '-';
echo
echo "Done!"
