#!/bin/bash
echo -e "  ____  _       _ _            _                       "
echo -e " / ___|(_) __ _| | | __ _ _ __| |__   ___  _ __ _ __   "
echo -e "| |  _ | |/ _  | | |/ _  |  _ |  _ \ / _ \|  __|  _ \  "
echo -e "| |_| || | (_| | | | (_| | |  | | | | (_) | |  | | | | "
echo -e " \____|/ |\__,_|_|_|\__,_|_|  |_| |_|\___/|_|  |_| |_| "
echo -e "     |__/                                              "
echo

echo "beta: 2.2"

echo
echo "Gjallarhorn is an imgur crawler"
echo "This program will check each site for the first file detected then check to see if the file is online or not."
echo "The summary will contain the list of live urls with objects and a list without the objects."
echo
echo
echo "Enter block of URLs then hit enter twice:"
echo
array=()
while IFS= read -r -p "" url; do
    [[ $url ]] || break
    array+=("$url")
done

grab=$(printf ' %s\n' "${array[@]}")

echo "---Anaylsis in Progress---"
echo
for i in $(echo $grab); do echo  "$i" ;
echo "$(curl -s $i > riaa-watch.txt
cat riaa-watch.txt | grep "mp4" > riaa-stage2.txt
key=$(awk 'NR==1 {print; exit}' riaa-stage2.txt | cut -d '"' -f2)
echo "$key"
echo "$key" >> keyrecord.txt
wget -S --spider $key 2>&1 | grep -q 'Remote file exists' && echo wGET: The file exists and is currently live. >> databank.txt && echo $i >> live.txt || echo $i >> faileddatabank.txt
) "; done

#Display Summary
echo "---Beta Script: Gjallarhorn---"
echo
echo "Live URLs with DMCA mp4 object"
echo "----------"
cat live.txt 2>/dev/null
echo
echo -e "Failed to Find object at these URLs"
echo "----------"
cat faileddatabank.txt 2>/dev/null
echo
echo "Number of logs"
cat keyrecord.txt | wc -l


#Clean Up Sys Files
rm databank.txt 2>/dev/null
rm keyrecord.txt 2>/dev/null
rm faileddatabank.txt 2>/dev/null
rm riaa-stage2.txt 2>/dev/null
rm riaa-watch.txt 2>/dev/null
rm live.txt 2>/dev/null

