#!/bin/bash

echo  ' \t' " _               _       _                 _            "
echo  ' \t' "| |__   ___  ___| |_    | |__  _   _ _ __ | |_ ___ _ __ "
echo  ' \t' "| '_ \ / _ \/ __| __|   | '_ \| | | | '_ \| __/ _ \ '__|"
echo  ' \t' "| | | | (_) \__ \ |_    | | | | |_| | | | | ||  __/ |   "
echo  ' \t' "|_| |_|\___/|___/\__|___|_| |_|\__,_|_| |_|\__\___|_|   "
echo  ' \t' "                   |_____|                              "
echo


echo "This program is designed to track domains that are moving between hosts rapidly, or hosted on more than one platform"
echo "If you would like to report an error ping drampil on slack."
echo
echo "Enter URL"
read url
echo
echo "Enter loop count - i.e. 5 or 50"
read count
echo
echo "Scan running please wait..."
echo

# break down the url
echo $url | grep -oE -m1 '[-+[:alnum:]]+[.][[:alnum:]+_.-]+' | sed 's/www.//' | head -1 > urledit.txt
value=$(<urledit.txt)


echo
echo "First Run"
# run the loop
for ((i=1;i<=$count;i++)); do host $value > ipsave1.txt
ip1=$(<ipsave1.txt)
echo whois $ip1 | awk 'NR==1 {print $5}' > whois1.txt
who1=$(echo whois $ip1 | awk 'NR==1 {print $5}')

if [[ $who1 == "alias" ]]
then
        rm whois1.txt
        cat ipsave1.txt | awk 'NR==2 {print $4}' > whois1.txt
        cat ipsave1.txt | awk 'NR==2 {print $4}' >>  ipcounter1.txt
else
        echo whois $ip1 | awk 'NR==1 {print $5}' >>  ipcounter1.txt
fi

who=$(<whois1.txt)
whois $who > stage1.txt 2>&1
cat stage1.txt | grep -m 1 -e 'OrgName' -e 'orgname' | awk '{print $2}' > stage21.txt
stage2=$(<stage21.txt)

# show loop results
echo -e  "Provider:" "$stage2"'\t'"IP Address: ""$who"'\t'"Time:" $(date +"%T") >> logs.txt
echo -e "$stage2" >> hosts1.txt; done
echo -e "IP(s) detected from JHD"
cat ipcounter1.txt | sort -u
echo
cat logs.txt
echo

# clean up system files
rm -f urledit.txt
rm -f ipsave1.txt
rm -f whois1.txt
rm -f stage1.txt
rm -f stage21.txt
rm -f logs.txt
rm -f ipcounter1.txt
rm -f hosts1.txt
sleep 3

echo "Second Run"
# run the loop
for ((i=1;i<=$count;i++)); do host $value > ipsave1.txt
ip1=$(<ipsave1.txt)
echo whois $ip1 | awk 'NR==1 {print $5}' > whois1.txt
who1=$(echo whois $ip1 | awk 'NR==1 {print $5}')

if [[ $who1 == "alias" ]]
then
        rm whois1.txt
        cat ipsave1.txt | awk 'NR==2 {print $4}' > whois1.txt
        cat ipsave1.txt | awk 'NR==2 {print $4}' >>  ipcounter1.txt
else
        echo whois $ip1 | awk 'NR==1 {print $5}' >>  ipcounter1.txt
fi

who=$(<whois1.txt)
whois $who > stage1.txt 2>&1
cat stage1.txt | grep -m 1 -e 'OrgName' -e 'orgname' | awk '{print $2}' > stage21.txt
stage2=$(<stage21.txt)

# show loop results
echo -e  "Provider:" "$stage2"'\t'"IP Address: ""$who"'\t'"Time:" $(date +"%T") >> logs.txt
echo -e "$stage2" >> hosts1.txt; done
echo -e "IP(s) detected from JHD"
cat ipcounter1.txt | sort -u
echo
cat logs.txt
echo


# clean up system files
rm -f urledit.txt
rm -f ipsave1.txt
rm -f whois1.txt
rm -f stage1.txt
rm -f stage21.txt
rm -f logs.txt
rm -f ipcounter1.txt
rm -f hosts1.txt
sleep 3

echo "Final Run"
# run the loop
for ((i=1;i<=$count;i++)); do host $value > ipsave1.txt
ip1=$(<ipsave1.txt)
echo whois $ip1 | awk 'NR==1 {print $5}' > whois1.txt
who1=$(echo whois $ip1 | awk 'NR==1 {print $5}')

if [[ $who1 == "alias" ]]
then
        rm whois1.txt
        cat ipsave1.txt | awk 'NR==2 {print $4}' > whois1.txt
        cat ipsave1.txt | awk 'NR==2 {print $4}' >>  ipcounter1.txt
else
        echo whois $ip1 | awk 'NR==1 {print $5}' >>  ipcounter1.txt
fi

who=$(<whois1.txt)
whois $who > stage1.txt 2>&1
cat stage1.txt | grep -m 1 -e 'OrgName' -e 'orgname' | awk '{print $2}' > stage21.txt
stage2=$(<stage21.txt)

# show loop results
echo -e  "Provider:" "$stage2"'\t'"IP Address: ""$who"'\t'"Time:" $(date +"%T") >> logs.txt
echo -e "$stage2" >> hosts1.txt; done
echo -e "IP(s) detected from JHD"
cat ipcounter1.txt | sort -u
echo
cat logs.txt
echo


# clean up system files
rm -f urledit.txt
rm -f ipsave1.txt
rm -f whois1.txt
rm -f stage1.txt
rm -f stage21.txt
rm -f logs.txt
rm -f ipcounter1.txt
rm -f hosts1.txt
