#!/bin/bash

#Read Input

read -p "Attacking IP Address: " ipadder

# Make the variables

url=$(echo $ipadder"/xmlrpc.php")
dank=$(curl -Iks -m 5 -A "AWS Trust and Safety" $url | grep 'HTTP' | awk '{print $2}')
echo "Checking..." $url
echo "Status code" $dank
echo
curl --verbose -Iks -m 5 -A "AWS Trust and Safety" $url
echo

# If and RESULTS
printf "%`tput cols`s"|tr ' ' '-';
if [[ $dank == 405 ]]
then
        echo "This Word Press is vulnerable to attacks and can accept POST requests."
elif [[ $dank == 403 ]] || [[ $dank == 404 ]]
then
        echo "This Word Press is secured."
else
        echo "Error somewhere, or this isn't a Word Press Infastructure."
        echo
fi
printf "%`tput cols`s"|tr ' ' '-';
echo
echo "Finished"
