#!/bin/bash
echo -e  ' \t' "  __  __                         _   _ ____  _     "
echo -e  ' \t' " |  \/  | ___  __ _  __ _    ___| | | |  _ \| |    "
echo -e  ' \t' " | |\/| |/ _ \/ _  |/ _  |  / __| | | | |_) | |    "
echo -e  ' \t' " | |  | |  __/ (_| | (_| | | (__| |_| |  _ <| |___ "
echo -e  ' \t' " |_|  |_|\___|\__, |\__,_|  \___|\___/|_| \_\_____|"
echo -e  ' \t' "              |___/                                "
echo
echo "Experimental Edition - please test for deobfuscation worthiness"
echo
echo "x-amz-apigw-id is the Gateway ID"
echo "x-amz-cf-id is CloudFront"
echo "If you would like to report an error ping drampil on slack."
echo
echo "Instructions"
echo "> Please enter a single URL, enter one URL per line,"
echo "> or paste all URLs at the same time as a code block."
echo "> Mega cURL will accept obfuscated URLs containing hxxp or [.] / [dot]"
echo "> To initiate press enter twice."
echo "---"

array=()
while IFS= read -r -p "" url; do
    [[ $url ]] || break
    array+=("$url")
done

grab=$(printf ' %s\n' "${array[@]}")
printf "%`tput cols`s"|tr ' ' '-';
echo
echo
for i in $(echo $grab | sed 's/[h]xx[p]/http/gi;' | awk '{gsub(/\[.\]/,".");}1' | awk '{gsub(/\[dot\]/,".");}1'); do echo ">" "$i";
echo "$(curl -I -s -L -k \
--show-error \
$i \
| grep 'HTTP\|Location\|location\|x-amz-apigw-id\|CloudFront\|x-amz-cf-id:\|AmazonS3' \
| grep -v 'onion-location\|via')"
echo; done

printf "%`tput cols`s"|tr ' ' '-';
echo
echo "Done!"
