#!/bin/bash

echo "If you would like to report an error ping drampil on slack."
echo
echo "Welcome to Snapshot - This attempts to parse the html from a website on a low level"
echo "Enter URL below"

read url

curl -L -s -k $url | sed 's/<script>.*<\/script>//g;/<script>/,/<\/script>/{/<script>/!{/<\/script>/!d}};s/<script>.*//g;s/.*<\/script>//g' > 1.txt

cat 1.txt | sed 's/<[^>]*>//g;' > 2.txt

cat 2.txt | sed '/^[[:space:]]*$/d;'

rm 2.txt
rm 2.txt
