#!/bin/bash
echo "Initiating Toy - Box update..."
sleep 1
echo
wget -N -nv https://raw.githubusercontent.com/drampil/toy-box/main/megac && chmod +x megac;
wget -N -nv https://raw.githubusercontent.com/drampil/toy-box/main/hosthunter && chmod +x hosthunter;
wget -N -nv https://raw.githubusercontent.com/drampil/toy-box/main/javelin && chmod +x javelin;
wget -N -nv https://raw.githubusercontent.com/drampil/toy-box/main/ghost && chmod +x ghost;
wget -N -nv https://raw.githubusercontent.com/drampil/toy-box/main/warpath && chmod +x warpath;
wget -N -nv https://raw.githubusercontent.com/drampil/toy-box/main/aris && chmod +x aris;
wget -N -nv https://raw.githubusercontent.com/drampil/toy-box/main/hostcheck && chmod +x hostcheck;
wget -N -nv https://raw.githubusercontent.com/drampil/toy-box/main/stinger && chmod +x stinger;
wget -N -nv https://raw.githubusercontent.com/drampil/toy-box/main/tessbeta && chmod +x tessbeta;
echo
echo "Installed or updated the following:"
echo
echo "1. Mega cURL"
echo -e "└──╼ ./megac"
echo "2. Host Hunter"
echo -e "└──╼ ./hosthunter"
echo "3. Javelin"
echo -e "└──╼ ./javelin"
echo "4. Ghost"
echo -e "└──╼ ./ghost"
echo "5. Warpath"
echo -e "└──╼ ./warpath"
echo "6. Aris-C"
echo -e "└──╼ ./aris"
echo "7. Tracer"
echo -e "└──╼ ./hostcheck"
echo "8. Imgr-C" 
echo -e "└──╼ ./stinger"
echo "9. Tesseract"
echo -e "└──╼ ./Tesseract"
echo
echo Done!
